/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_CPUFreqMeter
#define HEADER_CPUFreqMeter
/*
htop - CPUFreqMeter.h
(C) 2016 Petr Benes
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"

extern int CPUFreqMeter_attributes[];

extern MeterClass CPUFreqMeter_class;

#endif
