/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_CPUTempMeter
#define HEADER_CPUTempMeter
/*
htop - CPUTempMeter.h
(C) 2016 Petr Benes
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"

extern int CPUTempMeter_attributes[];

extern MeterClass CPUTempMeter_class;

#endif
